### ISSUE TITLE
Dropdown full width

### ISSUE THREAD

**Issue by rsboarder** [joo6077/cool_dropdown#1]
Hey! Big thx for this package, it's really very customizable but I need more :)

Is it possible to make dropdowns width based on result width?

Current situation is:
![image](https://user-images.githubusercontent.com/2170743/140655700-da2ad211-6b30-4e7a-ac75-a5851e3ef5e2.png)
And what I want to achieve:
![image](https://user-images.githubusercontent.com/2170743/140655709-11a6abfe-45a3-4651-8144-443f05e10e6c.png)

**Comment by joo6077** [comment]
Thank you for using my packages! I took your problems and I implemented
some code to fix your problems. You should update the cool dropdown to
1.4.0 and check onOpen and I set the dropdownWidth default value as
resultWidth.

**Comment by rsboarder** [comment]
@joo6077 `onOpen` works like a charm, thx! But if `resultWidth: double.maxFinite`, then dropdown doesn't appear.

**Comment by joo6077** [comment]
@rsboarder 
Hm.. I think you want to fit the resultbox as your screen width. 
I think the problem is ```double.maxFinite``` pass value to dropdownWidth as like 1.79808...+e something like this.
When I tested ```MediaQuery.of(context).size.width``` this worked well on dropdownWidth too(fit to screen width).
I would like to recommend you to use MediaQuery one! Do you have any special reasons?

**Comment by rsboarder** [comment]
@joo6077 yes, sry, I'm a newbie in flutter. Decided to wrap widget in `LayoutBuilder` and to pass `constraints.maxWidth`
